### ISSUE TITLE
抓取过程中出错

### ISSUE THREAD

**Issue by caoshuaijie** [fancyerii/wechat-gongzhonghao-crawler#11]
抓取过程中, 第一次存完库 报错:
Traceback (most recent call last):
  File "cli.py", line 54, in <module>
  File "crawler\__main__.py", line 340, in main
  File "crawler\wechatautomator.py", line 68, in get_wechat_id
UnboundLocalError: local variable 'wechat_id' referenced before assignment
[11688] Failed to execute script cli

**Comment by fancyerii** [comment]
微信什么版本，能不能截个图或者录个出错的视频

**Comment by caoshuaijie** [comment]
微信客户端3.1.0, 报错信息如下, 每次都是抓取200条文章左右
![1712122483724](https://github.com/fancyerii/wechat-gongzhonghao-crawler/assets/34123610/760748c6-2da5-40a3-9aa6-42a18c97e377)
![image](https://github.com/fancyerii/wechat-gongzhonghao-crawler/assets/34123610/a5e51517-322c-420a-be0c-a09322c6a725)

**Comment by caoshuaijie** [comment]
![image](https://github.com/fancyerii/wechat-gongzhonghao-crawler/assets/34123610/02a885d9-1ed2-434c-84bb-360b583ca66b)

**Comment by fancyerii** [comment]
你是抓取多个微信公众号，然后第一个成功，抓取第二个时出问题？你有没有关注“北京动物园”这个公众号？

**Comment by fancyerii** [comment]
另外执行：
```
java -cp wechat-crawler-server-xxx-jar-with-dependencies.jar com.github.fancyerii.wechatcrawler.server.service.DumpDebugInfo debug-info.txt
```
，看看debug-info.txt里有没有什么详细错误信息。

**Comment by fancyerii** [comment]
看代码，是抓取一次结束，然后sleep期间获取微信id时出错。在sleep期间，是不是微信失去了焦点？

**Comment by caoshuaijie** [comment]
只抓取一个公众号, 并且也关注了北京动物园, 我是在另外一台机器上连着虚拟机跑的, 抓取过程中, 没有任何电脑的操作 .

**Comment by caoshuaijie** [comment]
debug-info   ![image](https://github.com/fancyerii/wechat-gongzhonghao-crawler/assets/34123610/37ead3dc-c732-48a8-ae37-6e65b32f1da8)

**Comment by fancyerii** [comment]
有3个问题：
1. 有一些特殊的字符串无法存到content
请检查一下是否设置了mysql的相关配置：https://github.com/fancyerii/wechat-gongzhonghao-crawler?tab=readme-ov-file#%E4%BF%AE%E6%94%B9utf8%E7%BC%96%E7%A0%81

2. 抓取到100页时失败次数超过3次，退出。
根据我自己的经验，翻页太多是容易失败。这是由于这里抓取微信的实现机制导致的，你可以手工试一下翻页，如太多了也经常刷新失败。可能的解决方法是增加重试次数(no_item_retry)，这个请下载新的版本(v1.3.4)。但这不是根本解决方法，因为抓取的机制不太支持翻页过多。另外翻页过多也可能被微信的反抓取机制识别从而封号(没遇到过，只是猜测)。

3. sleep期间获取微信id时出错
可能是由2引起，v1.3.4的代码应该可以忽略这个问题。

**Comment by caoshuaijie** [comment]
重新下载了cli-v1.3.4.exe , 设置lock_input = true 在虚拟机上跑, 第一次入库后 虚拟机就卡死了, 得强制重启。
heartbeat表一直在更新， 心跳没有结束

**Comment by fancyerii** [comment]
> 重新下载了cli-v1.3.4.exe , 设置lock_input = true 在虚拟机上跑, 第一次入库后 虚拟机就卡死了, 得强制重启。 heartbeat表一直在更新， 心跳没有结束

错误信息能再发一下吗？

另外看一下微信占用的cpu/内存。如果翻页太多了，可能导致微信占用资源过多从而卡死。因为只有第一次抓取需要翻很多页，实在不行就手动重启一下。

**Comment by caoshuaijie** [comment]
机器直接卡死了 无法获取报错信息和微信占用资源情况, 得强制关电源. 
我配置的first_pages = 10, 第一次入库后就卡死

**Comment by fancyerii** [comment]
> 机器直接卡死了 无法获取报错信息和微信占用资源情况, 得强制关电源. 我配置的first_pages = 10, 第一次入库后就卡死

是cli-v1.3.4的问题吗？cli-v1.3.3没有这个问题？
