### ISSUE TITLE
initDataSource时报NPE

### ISSUE THREAD

**Issue by libhot** [fancyerii/wechat-gongzhonghao-crawler#12]
java -cp wechat-crawler-server-1.3.2-jar-with-dependencies.jar com.github.fancyerii.wechatcrawler.server.service.WechatCrawlerServer
2024-04-11 17:00:17.022 [main] INFO  s.s.StaticFilesConfiguration - StaticResourceHandler configured with folder = /public
Exception in thread "main" java.lang.NullPointerException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.antbrains.mysqltool.PoolManager.initDataSource(PoolManager.java:95)
        at com.antbrains.mysqltool.PoolManager.StartPool(PoolManager.java:144)
        at com.github.fancyerii.wechatcrawler.server.service.WechatCrawlerServer.main(WechatCrawlerServer.java:28)

已经按照说明在conf/dbConf.properties配置好
MYSQL_DRIVER=org.gjt.mm.mysql.Driver
MYSQL_URL=jdbc:mysql://localhost:3306/wechat
MYSQL_USER=wechat
MYSQL_PASS=mypass

**Comment by libhot** [comment]
似乎配置文件不对，
MYSQL_URL=jdbc:mysql://localhost:3306/wechat
应当是
MYSQL_URL=jdbc:mysql://localhost:3306/{db}

**Comment by fancyerii** [comment]
> 似乎配置文件不对， MYSQL_URL=jdbc:mysql://localhost:3306/wechat 应当是 MYSQL_URL=jdbc:mysql://localhost:3306/{db}

```
MYSQL_URL=jdbc:mysql://localhost:3306/${db}
```
